spring.application.name=backend-spring
server.port=8080

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3307/kanban_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/kanban_mongo

# JWT
jwt.secret=kanban-super-secret-key
jwt.expiration=86400000

# Logs
logging.level.org.springframework.security=DEBUG